#!/usr/bin/env sh
set -eu

exec 2>&1

COMMAND=/usr/bin/patroni
CONFIG=/etc/patroni/postgres0.yml
USER=postgres
GROUP=postgres

# set default value to PATRONI_POSTGRESQL_DATA_DIR
: "${PATRONI_POSTGRESQL_DATA_DIR:=/data/postgresql/data}"

if [ -z "$PATRONI_ETCD_HOST"];
then
   echo "env variable PATRONI_ETCD_HOST is not set"
   exit 1
fi

if [ -d ${PATRONI_POSTGRESQL_DATA_DIR} ];
then
   mkdir -p $PATRONI_POSTGRESQL_DATA_DIR
   chown -R $USER:$GROUP $PATRONI_POSTGRESQL_DATA_DIR
   chmod 750 $PATRONI_POSTGRESQL_DATA_DIR
fi

exec /sbin/chpst -u ${USER}:${GROUP} ${COMMAND} ${CONFIG}